#!/bin/bash

# Generate icon sizes from walletchan-icon.png
# Uses sips (macOS built-in) for image resizing

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
SOURCE_ICON="$PROJECT_ROOT/public/walletchan-icon.png"
ICONS_DIR="$PROJECT_ROOT/public/icons"

# Icon sizes needed for Chrome extension
SIZES=(16 48 128)

if [ ! -f "$SOURCE_ICON" ]; then
    echo "Error: Source icon not found at $SOURCE_ICON"
    exit 1
fi

mkdir -p "$ICONS_DIR"

for size in "${SIZES[@]}"; do
    output="$ICONS_DIR/icon${size}.png"
    echo "Generating ${size}x${size} icon..."
    sips -z $size $size "$SOURCE_ICON" --out "$output" > /dev/null
done

echo "Done! Icons generated in $ICONS_DIR"
ls -la "$ICONS_DIR"

# Generate base64 for WALLET_ICON in walletIcon.ts
GIF_ICON="$PROJECT_ROOT/public/walletchan-animated.gif"
WALLET_ICON_FILE="$PROJECT_ROOT/src/chrome/walletIcon.ts"

if [ -f "$GIF_ICON" ]; then
    echo ""
    echo "Generating wallet icon for EIP-6963..."

    # Generate base64 string from animated gif
    echo "Generating base64..."
    BASE64_ICON=$(base64 -i "$GIF_ICON" | tr -d '\n')
    DATA_URI="data:image/gif;base64,$BASE64_ICON"

    # Write to walletIcon.ts
    cat > "$WALLET_ICON_FILE" << EOF
// Auto-generated by scripts/generate-icons.sh
// Do not edit manually - run the script to update

export const WALLET_ICON = "$DATA_URI";
EOF

    echo "Updated WALLET_ICON in $WALLET_ICON_FILE"
else
    echo "Warning: $GIF_ICON not found, skipping base64 generation"
fi
